[package]
name = "docs"
version = "0.0.1"
edition = "2021"
build = "build.rs"
publish = false

[build-dependencies]
skeptic = "0.13.7"
tokio = "1.36.0"

[dev-dependencies]
skeptic = "0.13.7"
starkbiter-core.workspace = true
starkbiter-bindings.workspace = true
# revm-primitives.workspace = true
